"""initial

Revision ID: 379de30799da
Revises: 
Create Date: 2025-11-21 23:49:36.893041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379de30799da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.Column('path', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph')
    # ### end Alembic commands ###
